name: Build repo
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Making input directory
        run: mkdir /tmp/stuff
        
      - name: Copying files
        run: cp -r . /tmp/stuff

      - name: Deleting files
        run: rm -rf * && rm -rf /tmp/stuff/.git*

      - name: Downloading blogging software...
        run: git clone https://github.com/greysoh/blog-gen.git

      - name: Installing blogging software...
        run: cd blog-gen && npm install

      - name: Running blogging software...
        run: cd blog-gen && cp -r /tmp/stuff in && npm start

      - name: Listing files (for debugging)
        run: cd blog-gen && ls out

      - name: Downloading blog...
        run: git clone https://github.com/greysoh/greysoh.github.io.git pages
      
      - name: Deleting existing files...
        run: rm -rf pages/*
      
      - name: Copying new files...
        run: cp -r blog-gen/out/* pages/
      
      - name: Setting config...
        shell: bash
        env: 
          EMAIL: ${{ secrets.EMAIL }}
          PASS: ${{ secrets.TOKEN }}
        run: git config --global user.name "greysoh" && git config --global user.email "$EMAIL"
      
      - name: Commiting changes...
        run: cd pages && git add . && git commit -m "Sync changes"

      - name: Pushing changes...
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source-directory: 'pages'
          destination-github-username: 'greysoh'
          destination-repository-name: 'greysoh.github.io'
          user-email: ${{ secrets.EMAIL }}
          target-branch: main
